;Important Save Using Encode UTF-8 For Avoid Error Text


[LAUNCHER]
;---------------------------------------
;PublicVersion Can Edit On AssemblyInfo.cs orAssemblyVersion
;--------------------------------------
launcherversion=2022.0.0.0

;---------------------------------------
;1= Maintenance 
;2= Matenance + Alert
;3= Status normal
;4= Status normal + Alert
;--------------------------------------
status=3

;---------------------------------------
;Use \n Untuk Menambah Paragraph
;---------------------------------------
message=Your Message

webpage=http://localhost/HTDOCS/launcher/New_Launcher/NEWS/Point%20Blank.html
userlist=1ca32662427267f6393a3d87063e0031
files=http://localhost/HTDOCS/files/

[UPDATE]
updateurl=http://localhost/HTDOCS/updates/
clientversion=1

[GAME]
keyhost=false
key=0
use_xingload=false
BanHWID=http://localhost/HTDOCS/ban/ban_hwid.txt

[CONFIG]
GameVersionn=1.15.42 (v42)
FilesCountCompare=5
login_form=1
version_game=1.15.42

[LAUNCHER_BAN]
BanPerm=http://localhost/launcher/ban/BANNED.ban